### ISSUE TITLE
Can't use a dependency with ormlite annotations.

### ISSUE THREAD

**Issue by aberaud** [j256/ormlite-android#142] opened 2022-09-29 16:24 UTC
Related to https://github.com/j256/ormlite-android/issues/141

Since `ormlite-android` 6 embeds `ormlite-core` classes, it seems like it's not possible to use a non-Android java dependency with ormlite-annotated classes, from an Android project using ormlite-android to store the objects provided by this dependency.

Importing the non-Android dependency (which uses ormlite-core) results in duplicate class errors (as described in https://github.com/j256/ormlite-android/issues/141 )

**Comment by j256** [comment] 2022-10-04 19:02
So this is a duplicate of #141 ?  Did you just post this to get my attention or is the more to the issue?

**Comment by aberaud** [comment] 2022-10-04 19:09
The original ticket was initially closed as "working as expected", so I opened this other ticket that more specifically describes the root problem instead of the symptoms (while honestly also hoping to get your attention). Since the other ticket was reopened, one of these could be closed as a duplicate.

**Comment by j256** [comment] 2022-10-05 23:41
I've reopened that ticket.

**Closed as completed by j256** 2022-10-05 23:41 UTC
